### ISSUE TITLE
Header problem

### ISSUE THREAD

**Issue by cbournak** [SimonPadbury/bst#10]
If "Front page displays" is set to "Your latest posts" there is a "Warning: Cannot modify header information - headers already sent by (output started at /wp-content/themes/bst-master/includes/header.php:4) in /wp-includes/pluggable.php on line 1178" that shows up.

**Comment by SimonPadbury** [comment]
Hi cbournak,

The error is not showing for me (although I do have the config debug set to true). I just made some changes to the BST header.php based on the information here [http://codex.wordpress.org/FAQ_Troubleshooting#How_do_I_solve_the_Headers_already_sent_warning_problem.3F](http://codex.wordpress.org/FAQ_Troubleshooting#How_do_I_solve_the_Headers_already_sent_warning_problem.3F). Please let me know of this solves the problem.

Thanks,

Simon

**Comment by SimonPadbury** [comment]
OK, I have removed the PHP comment at the end of includes/header.php and instead put the example site-title within a regular HTML comment.

This shouldn't have given you any problems, however, because this PHP was embedded into HTML and therefore it should have had its closing "?>" .

**Comment by mentolnet** [comment]
Hello Simon.
Unfortunately, i´m having the same problem:
"Warning: Cannot modify header information - headers already sent by (output started at /home/mentolne/public_html/terradrone/wp-content/themes/bst-master/includes/header.php:4) in /home/mentolne/public_html/terradrone/wp-includes/pluggable.php on line 1178"
I recently built a website using your files (i think with the previous version) and everything was OK.
Any ideas? Thank you.

**Comment by SimonPadbury** [comment]
Hi,

I will try to fix this tomorrow. Meanwhile,

If you copy header.php to the theme root folder, an on index.php use get_header(); instead of get_template_part(...); dose the warning go away?

**Comment by SimonPadbury** [comment]
Hi,

I've been though the Theme again, and I can't find anything causing this warning.

My research and notes:

(1.)  https://wordpress.org/support/topic/cannot-modify-header-information-headers-already-sent-4

When I search the internet for other people who are seeing the same warning message on other themes, the reason and solution (almost*) always is: there are trailing white spaces at the end of `functions` files – remove these and the warning goes away. 

[*Note also that sometimes a plugin can cause a similar warning. So maybe you need to disable all plugins and see whether the the warning goes away, then re-activate them until you find the warning reappear.]

I have removed all white spaces and newlines from the end of `functions.php` and all the files in the `functions/` folder. And upon recommendation, I have also removed the closing `?>` from these files too. See this for why – even though this blog post is about plugins:

(2.) http://hardcorewp.com/2013/always-omit-closing-php-tags-in-wordpress-plugins/

(3.)  https://codex.wordpress.org/FAQ_Troubleshooting#How_do_I_solve_the_Headers_already_sent_warning_problem.3F

If the problem is not in the **theme**, I ask: did you edit the WordPress file  `config.php`? (for turing debugging true/false).

It appears that some code editors add a newline every time you open a file – placing the cursor on the newline at the end of your code. So maybe extra (invisible) stuff is being added to your functions files when you open and work on them. (The GitHub online editor does this, so I am careful to remove trailing whitespace / newlines if I use it.) 

(4.) http://www.hongkiat.com/blog/wordpress-error-warning-cannot-modify-header-information/

(5.) http://nickroshon.com/wordpress/how-to-fix-warning-cannot-modify-header-information-headers-already-sent-error-message-in-wordpress

Removal of trailing whitespace has always solved this problem for me; I don't know what else to suggest.

**Comment by mentolnet** [comment]
Hello again.
This is a fresh install with no changes whatsoever to any of the files. I don´t have any plugins installed, not even Askimet or Hello Dolly.
I downloaded WBST and the same is happening. The strange thing is that, as i told you, i didn´t have any problems the last time i used any of these themes with the same setup.
Is there a way i can have access to the previous version?

**Comment by SimonPadbury** [comment]
I think there's a way to get old versions form GitHub – sorry I don't have old versions on my computer as I overwrite them.

After Googling a lot and going over responses in Stack Overflow (e.g. http://stackoverflow.com/questions/12769982/reference-what-does-this-error-mean-in-php/12770075#12770075), all I can find to fix this problem is – what I said previously. 

There are YouTube videos explaining how to fix this problem. E.g. https://www.youtube.com/watch?v=stDskny5Sec

And if you're still stuck, try this:

1. Note from the error message **what file** the error is in.
2. **Even it the file is in the WordPress core** open it and delete any white space before the opening `<?php` and after the final `?>` (or at the end of the file of there is no final `?>`.  _Do this anyway, even if there is no white space that you can see._
3. Then save it and refresh the browser.

That's all I can suggest.

**Comment by mentolnet** [comment]
Hello again, Simon. And thank you for your tips.
In fact, i read your explanation before i downloaded version 2.5 and i followed the suggestions from your previous message. I am afraid the problem continues with all the themes i tried (bst and wbst).
I opened the functions file of both themes and deleted any blank space at the end of the file. I did the same with all the files present inside the "functions" folder, even.
The error i´m seeing remains the same. I have no idea where to turn next...

**Comment by mentolnet** [comment]
Hello Simon.
Just to let you know that i´ve installed everything from scratch (WordPress and your theme and child-theme) and everything is working now.
Thanks for your input. All the best!

**Comment by SimonPadbury** [comment]
Hello mentolnet,

Thanks for that confirmation. I really believe there's no problem here -- the warning doesn't show for me. And all the solutions for this "headers already sent" warning ae already included in BST, WBST and BST-Plus.

**Comment by mentolnet** [comment]
That was my initial thought and the reason i decided to try a fresh install.
Thank you once more.

**Comment by mentolnet** [comment]
Hello again, Simon. I am sorry to disturb you again but i have a question for you. Yesterday, as i told you, i made a fresh install with BST and everything was working fine.
I didn´t touch it, as i was finishing other projects, and this morning when i was about to start working on this new website using your theme, magically the same message appears (headers already sent...). I am completely lost about what to do and so i decided to ask you if you think this could have something to do with the php version my server uses? I have no idea, really, but this just came to my head. The php version is 5.4.36.
Thank you once more.

**Comment by SimonPadbury** [comment]
Hi Mentolnet,
I don't now what could be the cause, but most of my Google searches for this "header already sent" warning say that the problem can be solved by removing empty space/characters from before the opening <? tag and/or from the end of theme functions files, WordPress config files, plugin functions files, etc.
Not only WordPress, but other PHP systems can get the "headers already sent" error. Maybe this somtains something that will help you: http://stackoverflow.com/questions/8028957/how-to-fix-headers-already-sent-error-in-php – but 

Sorry that doesn't help you -- you and I have tried all that. But can you try this, to probe that BST is or isn't the problem: make the header simpler, and see whether this (permanently) solves the problem, as follows:

1. Copy the header.php to the Theme root folder (same folder as index.php).2. In index.php, change it to <?php get_header(); ?> instead of the <? get_template_part(includes/header); ?>
       [Later, if this gets it working, you can make the same change to single.php, page.php and your other templates.]3. Is it working OK (is the homepage showing in the browser)?
If there's still a problem, then try this:
4. Go in to functions/enqueues.php In the new header.php and /*comment out*/ all the 'enqueue' and 'register' stuff for all the stylesheets and javascripts.5. Go into your new header again (created in 1. above) and build the links to each stylesheet and javascript, e.g.
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css" media="all"><link rel="stylesheet" type="text/css" href="css/bst.css" media="all">...
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script><script type="text/javascript" src="js/bst.js"></script>...        [Later, if this gets it working, you can move some of your <script> links down to the footer.php .]

If you are still not able to get the homepage to load in the browser, then the problem is not with BST (or whichever of my themes you're using). I don't know what the problem is after that – it could be one of your plugins, or WordPress.
Let me know how you get on with this.
Kind regards,
Simon

**Comment by mentolnet** [comment]
Hello Simon and, once again, thank you for the support given.
I decided to write a test post to see how another theme behaved and i´ve found out that the headers already sent error i was having with BST are completely gone after i did this.
So, to sum things up, all seems to work perfectly as long as the website is not empty.

Thank you and all the best to you.

**Comment by SimonPadbury** [comment]
Hi mentolnet

Thank you for this news.

All the best to you too.

Simon
